[project]
name = "audibleintegers"
version = "0.1.0"
dependencies = [
 	"numpy",
	"scipy",
	"matplotlib",
]

authors = [
    {name = "John A. Moon"},
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages]
find = {}
